services:
  backend:
    container_name: transcribe-translate-backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - whisper_models:/app/whisper_models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - tt-network

  frontend:
    container_name: transcribe-translate-frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - tt-network

  nginx:
    container_name: transcribe-translate-nginx
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - frontend
      - backend
    networks:
      - tt-network

volumes:
  whisper_models:

networks:
  tt-network:
    driver: bridge
