name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  build-and-push:
    name: Build and Push Docker Images to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set this in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set this in GitHub Secrets

      # Step 3: Build and push backend image
      - name: Build and Push Backend Image
        run: |
          docker build -t notys/transcribe-translate-backend:latest ./backend
          docker push notys/transcribe-translate-backend:latest

      # Step 4: Build and push frontend image
      - name: Build and Push Frontend Image
        run: |
          docker build -t notys/transcribe-translate-frontend:latest ./frontend
          docker push notys/transcribe-translate-frontend:latest

      # Step 5: Build and push nginx image
      - name: Build and Push Nginx Image
        run: |
          docker build -t notys/transcribe-translate-nginx:latest ./nginx
          docker push notys/transcribe-translate-nginx:latest
