name: Build and Push Docker Images to GitHub Container Registry

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  build-and-push:
    name: Build and Push Docker Images to GHCR
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}  # GitHub username
          password: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions

      # Step 3: Build and push backend image
      - name: Build and Push Backend Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/transcribe-translate-backend:latest ./backend
          docker push ghcr.io/${{ github.repository_owner }}/transcribe-translate-backend:latest

      # Step 4: Build and push frontend image
      - name: Build and Push Frontend Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/transcribe-translate-frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository_owner }}/transcribe-translate-frontend:latest

      # Step 5: Build and push nginx image
      - name: Build and Push Nginx Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/transcribe-translate-nginx:latest ./nginx
          docker push ghcr.io/${{ github.repository_owner }}/transcribe-translate-nginx:latest
