name: Build and Push Docker Images to GitHub Container Registry

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  build-and-push:
    name: Build and Push Docker Images to GHCR
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build and push backend CUDA and non-CUDA images
      - name: Build and Push Backend CUDA Image
        run: |
          lower_owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$lower_owner/transcribe-translate-backend:cuda ./backend
          docker push ghcr.io/$lower_owner/transcribe-translate-backend:cuda

      - name: Build and Push Backend Non-CUDA Image
        run: |
          lower_owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$lower_owner/transcribe-translate-backend:cpu ./backend --build-arg USE_CUDA=false
          docker push ghcr.io/$lower_owner/transcribe-translate-backend:cpu

      # Step 4: Build and push frontend image (same for both versions)
      - name: Build and Push Frontend Image
        run: |
          lower_owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$lower_owner/transcribe-translate-frontend:latest ./frontend
          docker push ghcr.io/$lower_owner/transcribe-translate-frontend:latest

      # Step 5: Build and push nginx image (same for both versions)
      - name: Build and Push Nginx Image
        run: |
          lower_owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$lower_owner/transcribe-translate-nginx:latest ./nginx
          docker push ghcr.io/$lower_owner/transcribe-translate-nginx:latest
